### ISSUE TITLE
[EPIC] Automatic dependency management opportunity

### ISSUE THREAD

**Issue by alexisdondon** [InseeFrLab/images-datascience#10]
We could discuss about managing dependency management like this:
https://docs.renovatebot.com/modules/manager/regex/

For exemple for binaries like code-server, rstudio etc.

- [x] list all ARG ENV that could be followed like this in this issue below as todo

binaries/dependency seen as opportunity to be included in renovate.json

langages:
- python,r,julia should we?

binaries currently having control on version installed:
- [x] vault client
- [x] vscode coder/code-server
- [x] rstudio
- [x] quarto (both r and python and rstudio reinstall again...)
- [x] mambaforge 
- others to add ?

For r R_VERSION track rocker script then R_STUDIO and S6 follow stable from install scripts.

binaries with no control version instal latest by package manager
- helm, kubectl, minio-client
- jupyterlab and co
- python all python environment.yml
- r a lot by rocker script or default package installation
- code-server extension (but dont know what we could do)

spark:
- should we do a tiny docker image or zip release on https://github.com/InseeFrLab/Spark-hive and do renovate PR on this when we publish new release
- pythonpath seems messy with py4j

docker images base in workflow:
- [11.7.1-base-ubuntu20.04](https://hub.docker.com/layers/cuda/nvidia/cuda/11.7.1-base-ubuntu20.04/images/sha256-f5a173f6829640d914097148eebb2427f2c5fd8570701c1bb8c4c99eb280e20e?context=explore)

**Comment by alexisdondon** [comment]
A renovate file has been added as en example on vscode version.
