### ISSUE TITLE
[EPIC] enhance workflow for building images

### ISSUE THREAD

**Issue by alexisdondon** [InseeFrLab/images-datascience#5]
We made the current choice :

- [x] trying to add some test on docker images for the moment we are trying container-structure-test
- [x] having one manual workflow that could build - test -push each image on latest tag
- [x] #28
- [x] #22
- [x] upgrade the manuel workflow pipeline to a schedule one implementing previous decisions
- [x] #8
- [x] discuss about the opportunity to rebuild the only images necessary based on folder changed by the commit
- [x] discuss about the opportunity to split r and python chain build images

**Comment by alexisdondon** [comment]
this run completed for gpu and cpu https://github.com/InseeFrLab/images-datascience/actions/runs/2722618773 but need to be confrmed as one i hit the 14Go runner on jupyter-python-gpu but don'kt know really why
